version: "3.8"

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile.app
    ports:
      - "8000:8000"
    volumes:
      - ../src:/app/src
    environment:
      - PYTHONUNBUFFERED=1

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db
